Repository ArnoldSmith86/virtualtabletop, pull requests merged in 2021-05, with the labels that each got.

#396 grids can now set any property on widgets
  client/js/widgets/widget.js
Labels: enhancement, widget properties

#397 fixed site layout when aspect ratio is close to 16:10
  assets/icons-white/hide side bar.svg
  client/css/layout.css
  client/js/main.js
  client/room.html
Labels: bug, user interface

#350 Add collections to ROTATE, SHUFFLE and SORT and improve sorting for SORT and SELECT
  client/js/jsonedit.js
  client/js/widgets/widget.js
Labels: enhancement, routine operations

#285 adds properties to change color of options svg
  client/js/widgets/spinner.js
Labels: enhancement

#406 added changeRoutine, enterRoutine and leaveRoutine
  client/components/deckEditor.js
  client/js/editmode.js
  client/js/jsonedit.js
  client/js/main.js
  client/js/mousehandling.js
  client/js/serverstate.js
  client/js/statemanaged.js
  client/js/widgets/basicwidget.js
  client/js/widgets/button.js
  client/js/widgets/card.js
  client/js/widgets/deck.js
  client/js/widgets/holder.js
  client/js/widgets/label.js
  client/js/widgets/pile.js
  client/js/widgets/spinner.js
  client/js/widgets/widget.js
  tests/client/widget-click.test.js
  tests/client/widget-count.test.js
Labels: enhancement, routine operations, widget properties

#433 fixed deck editor after changeRoutine PR
  client/components/deckEditor.js
Labels: bug, user interface

#440 fixed dropping a pile onto another pile
  client/js/widgets/widget.js
Labels: bug

#436 fixed some edge cases with default values
  client/js/jsonedit.js
  client/js/statemanaged.js
  client/js/widgets/widget.js
Labels: bug, widget properties

#437 only show games list for an empty room once
  client/js/serverstate.js
Labels: bug, user interface

#438 fixed disappearing children of cards, basicwidgets and buttons
  client/css/widgets/card.css
  client/css/widgets/label.css
  client/css/widgets/spinner.css
  client/js/domhelpers.js
  client/js/widgets/basicwidget.js
  client/js/widgets/button.js
  client/js/widgets/card.js
  client/js/widgets/spinner.js
Labels: bug

#417 Return null for undefined properties
  client/js/statemanaged.js
  client/js/widgets/widget.js
Labels: bug, routine operations, widget properties

#307 replace COMPUTE, RANDOM and applyVariables by operation strings and inline variables
  client/css/jsonedit.css
  client/js/jsonedit.js
  client/js/main.js
  client/js/widgets/card.js
  client/js/widgets/deck.js
  client/js/widgets/widget.js
  server/fileupdater.mjs
  tests/client/widget-count.test.js
  tests/testcafe/tests.js
Labels: enhancement, needs file version bump, routine operations

#408 Adds Timer widget and related features
  assets/button-icons/White-Play_Pause.svg
  assets/button-icons/White-Reset.svg
  client/css/widgets/timer.css
  client/js/editmode.js
  client/js/jsonedit.js
  client/js/serverstate.js
  client/js/widgets/timer.js
  client/js/widgets/widget.js
  client/room.html
  server/minify.mjs
  server/pcioimport.mjs
Labels: PCIO compatibility, enhancement, widget properties

#476 apply fileupdater to CLONE properties and fix version in downloaded states
  server/fileupdater.mjs
  server/room.mjs
Labels: bug

#456 Fixes mobile JSON input
  client/css/editmode.css
Labels: bug, user interface

#488 added simple JSON editor command to add a dynamic expression
  client/js/jsonedit.js
Labels: JSON editor, enhancement
