Repository ArnoldSmith86/virtualtabletop, pull requests merged in 2021-12, with the labels that each got.

#174 added dynamicProperties to face objects
  client/components/deckEditor.js
  client/js/editmode.js
  client/js/jsonedit.js
  client/js/widgets/card.js
  server/fileupdater.mjs
  tests/testcafe/tests.js
Labels: enhancement, needs file version bump, widget properties

#905 pile customization
  client/css/widgets/pile.css
  client/js/widgets/card.js
  client/js/widgets/pile.js
  client/js/widgets/widget.js
  server/pcioimport.mjs
Labels: enhancement, widget properties

#646 added `preventPiles` to disable pile formation in holders
  client/js/widgets/holder.js
Labels: enhancement, widget properties, pile related

#898 introduced a button that moves a room to a beta server
  .gitignore
  client/js/main.js
  client/js/overlays/states.js
  client/room.html
  config.template.json
  package.json
  server.mjs
  server/config.mjs
  server/minify.mjs
  server/player.mjs
  server/room.mjs
Labels: maintenance

#953 fixed asset upload
  server.mjs
Labels: bug

#608 AUDIO Function
  assets/icons-white/mute-svg.svg
  assets/icons-white/unmute-svg.svg
  client/css/layout.css
  client/js/jsonedit.js
  client/js/main.js
  client/js/statemanaged.js
  client/js/widgets/widget.js
  client/room.html
Labels: enhancement, user interface, routine operations

#920 fixed external properties `cardDefaults` and `cardType`
  client/js/jsonedit.js
Labels: bug, JSON editor

#931 PCIO import improvements
  server/pcioimport.mjs
Labels: bug, enhancement, PCIO compatibility

#974 Fixed extra edit appearing.
  client/css/layout.css
Labels: bug, user interface

#975 Long variant name display fix
  client/css/overlays/states.css
Labels: bug, user interface

#985 fixed "Update variant using current room state"
  client/js/overlays/states.js
Labels: bug, user interface

#987 fix JSON editor commands with options
  client/css/jsonedit.css
  client/js/jsonedit.js
Labels: bug, JSON editor

#992 fix adding composite widgets
  client/js/editmode.js
Labels: bug, JSON editor

#903 fix alignment issues and improve droptarget selection
  client/js/geometry.js
  client/js/main.js
  client/js/mousehandling.js
  client/js/widgets/canvas.js
  client/js/widgets/widget.js
Labels: bug

#995 fix automated `Production Environment` test
  .github/workflows/production-environment.yml
  client/js/widgets/widget.js
Labels: bug, maintenance

#999 Fix some timer problems
  client/js/jsonedit.js
  client/js/widgets/timer.js
Labels: bug

#1013 Select closest valid dropTarget
  client/js/widgets/widget.js
Labels: widget properties

#988 removed highlighting of the hotkey from JSON editor
  client/js/jsonedit.js
Labels: bug, JSON editor

#1009 Update input overlay widget updates
  client/css/jsonedit.css
  client/css/layout.css
  client/js/domhelpers.js
  client/js/widgets/widget.js
Labels: enhancement, user interface

#1004 Editor QoL improvements
  client/room.html
  server/minify.mjs
Labels: maintenance

#980 Informational overlay revamps
  assets/branding/discord-logo.svg
  assets/branding/github-logo.svg
  client/css/overlays/about.css
  client/css/overlays/connectionlost.css
  client/js/main.js
  client/room.html
  server/minify.mjs
Labels: enhancement, user interface

#1027 fixed massive memory leaks
  package.json
  server/room.mjs
  server/websocket.mjs
  tests/server/loadtest.js
Labels: bug, maintenance

#989 log multiple routine calls if they happen with the same mouse interaction
  client/js/jsonedit.js
Labels: enhancement, JSON editor

#1035 JSON editor tree view no longer steals focus
  client/js/jsonedit.js
Labels: bug, JSON editor

#1040 Make expander arrows in the JSON editor red if one of their descendants has a problem
  client/css/jsonedit.css
  client/js/jsonedit.js
Labels: enhancement, JSON editor

#1036 new `.pinPiece` and `.classicPiece` css
  client/css/widgets/classes.css
  client/js/editmode.js
  server/fileupdater.mjs
  tests/testcafe/tests.js
Labels: needs file version bump

#1038 Exclude audio property from inheritFrom
  client/js/statemanaged.js
Labels: bug

#1039 Clear erroneous audio element when invalid audio
  client/js/widgets/widget.js
Labels: bug
