Repository ArnoldSmith86/virtualtabletop, pull requests merged in 2021-08, with the labels that each got.

#705 Updates to how Deck Editor deals with data
  client/components/deckEditor.js
  client/js/editmode.js
Labels: needs testing

#548 improved debug output
  client/css/jsonedit.css
  client/js/jsonedit.js
  client/js/widgets/widget.js
  client/room.html
  tests/client/widget-click.test.js
  tests/client/widget-count.test.js
  tests/testcafe/tests.js
Labels: enhancement, JSON editor, Ready for review

#733 updated ws to 8.2.0
  package-lock.json
  package.json
  server/websocket.mjs
Labels: npm dependencies
