Repository ArnoldSmith86/virtualtabletop, pull requests merged in 2021-11, with the labels that each got.

#857 fixed crash when `ROTATE`ing a collection while JSON editor is active
  client/js/widgets/widget.js
Labels: bug, JSON editor

#848 changed minimum of duplication option `# Copies X` to 0
  client/js/jsonedit.js
Labels: bug, JSON editor

#849 added toggle for wide/narrow sidebar to JSON editor
  client/css/jsonedit.css
  client/js/jsonedit.js
  client/js/main.js
  client/js/tracing.js
  client/room.html
Labels: enhancement, JSON editor

#870 fixed GitHub workflows
  .github/workflows/production-environment.yml
  .github/workflows/testcafe.yml
Labels: bug, maintenance

#869 fixed loading vttc files
  server/fileloader.mjs
Labels: bug

#886 Fix debug information for INPUT
  client/js/widgets/widget.js
Labels: bug, JSON editor

#881 Implement anonymous collections.
  client/js/widgets/widget.js
Labels: enhancement, Ready for review

#889 fixed `IF` and `GET` debug output
  client/js/widgets/widget.js
Labels: bug, JSON editor

#908 fixed missing widgets in JSON editor F-keys
  client/js/jsonedit.js
Labels: bug, JSON editor

#927 Update fix for Chrome favicon to use the SVG version.
  client/room.html
Labels: bug, user interface

#918 more usable space for the classic JSON edit overlay
  client/css/editmode.css
  client/room.html
Labels: enhancement, user interface

#913 add `clickable` support and `artist` to canvas
  client/js/widgets/canvas.js
Labels: enhancement, widget properties

#924 improved multitouch resilience
  client/js/mousehandling.js
Labels: bug, user interface

#919 add support for floats with `LABEL`
  client/js/widgets/widget.js
Labels: bug, routine operations

#890 fixed `grid` in conjunction with `fixedParent`
  client/js/jsonedit.js
  client/js/widgets/widget.js
Labels: bug, widget properties

#925 only remove Guests from players if no player has the name
  server/room.mjs
Labels: bug

#916 added inverted properties to `inheritFrom`
  client/js/statemanaged.js
Labels: enhancement, widget properties
