Repository ArnoldSmith86/virtualtabletop, pull requests merged in 2021-02, with the labels that each got.

#49 added a "Split pile" feature to the pile "context menu"
  client/js/widgets/pile.js
Labels: User Interface

#175 Enhancement #146 add a thisID and thisButton
  client/js/widgets/button.js
Labels: enhancement

#180 applyVariables with property and template functionality
  client/js/widgets/button.js
Labels: enhancement

#176 added a new keyboard focused JSON editor
  client/css/jsonedit.css
  client/js/jsonedit.js
  client/js/main.js
  client/js/mousehandling.js
  client/js/serverstate.js
  client/js/widgets/widget.js
  client/room.html
  server/minify.mjs
Labels: enhancement

#199 added svgReplaces to BasicWidget and card face objects
  client/js/main.js
  client/js/widgets/basicwidget.js
  client/js/widgets/card.js
Labels: enhancement

#168 rooms cleanup unused files on the server
  server/room.mjs
Labels: operations

#222 added try-except around client message jsons
  server/connection.mjs
Labels: maintenance

#165 added the possibility to get memory dumps
  .gitignore
  server.mjs
Labels: maintenance

#227 presets for online IDE Gitpod
  .gitpod.yml
  .theia/launch.json
  .theia/settings.json
  README.md
  package.json
Labels: enhancement

#217 Eliminate duplicate applyVariables code in #214
  client/js/widgets/button.js
Labels: enhancement

#226 don't hide card child widgets
  client/css/widgets/card.css
Labels: bug
