Repository ArnoldSmith86/virtualtabletop, pull requests merged in 2021-09, with the labels that each got.

#691 Fix: Sort without valid key causes client to crash
  client/js/widgets/widget.js
Labels: routine operations

#711 Remove width/height equal to cardDefault/cardType
  client/js/jsonedit.js
Labels: JSON editor

#616 Remove Ctrl key actions for buttons in JSON editor
  client/js/jsonedit.js
Labels: enhancement, JSON editor

#761 Re-layout of Players Overlay
  client/css/layout.css
  client/css/overlays/players.css
  client/js/overlays/players.js
  client/room.html
Labels: user interface

#765 Adjust for viewport units on mobile
  client/css/layout.css
  client/js/main.js
Labels: bug

#782 Select max widgets *after* pile resolution, not before.
  client/js/widgets/widget.js
Labels: bug
