Repository ArnoldSmith86/virtualtabletop, pull requests merged in 2021-04, with the labels that each got.

#290 cards now check if their supplied deck is actually a deck
  client/js/widgets/card.js
Labels: bug

#284 crash fixes for JSON editor + "go to error" command
  client/js/jsonedit.js
Labels: bug

#338 fixed that you couldn't edit holder classes through JSON anymore
  client/components/baseEditOverlay.js
  client/js/editmode.js
  client/js/jsonedit.js
Labels: bug

#197 clickRoutine now in every widget and added CALL
  .gitpod.yml
  .theia/launch.json
  client/js/jsonedit.js
  client/js/mousehandling.js
  client/js/widgets/basicwidget.js
  client/js/widgets/button.js
  client/js/widgets/card.js
  client/js/widgets/pile.js
  client/js/widgets/spinner.js
  client/js/widgets/widget.js
  package.json
  server/minify.mjs
  tests/client/client-util.js
  tests/client/widget-click.test.js
  tests/client/widget-count.test.js
Labels: enhancement

#286 fixed a few problems with CLONE and DELETE
  client/js/editmode.js
  client/js/serverstate.js
  client/js/widgets/pile.js
  client/js/widgets/widget.js
Labels: bug

#353 fixed undefined collection after CALL and thisID+thisButton now point to the callee
  client/js/widgets/widget.js
Labels: bug

#354 RECALL now works with multiple decks in a holder
  client/js/widgets/widget.js
Labels: bug

#355 fixed edit mode display of checkers and pin pieces and font size of spinners
  client/css/widgets/classes.css
  client/js/widgets/spinner.js
Labels: bug

#364 changes to cardDefaults, cardTypes and faceTemplates now take effect immediately
  client/js/widgets/deck.js
Labels: bug

#369 Added bulk upload card images feature
  client/components/deckEditor.js
  client/js/editmode.js
  client/js/main.js
Labels: enhancement

#311 added a JSON editor command that copies the state from another room/server
  client/js/jsonedit.js
  server.mjs
Labels: JSON editor, enhancement

#83 changed SELECT mode default to "set" and added FileUpdater that migrates existing buttons
  client/js/widgets/widget.js
  package-lock.json
  package.json
  server/fileloader.mjs
  server/fileupdater.mjs
  server/room.mjs
  tests/testcafe/tests.js
Labels: enhancement, needs file version bump

#365 IF operation
  client/js/jsonedit.js
  client/js/widgets/widget.js
Labels: enhancement, routine operations

#383 additional GET aggregations
  client/js/jsonedit.js
  client/js/widgets/widget.js
Labels: enhancement, routine operations

#171 fixed that SELECT type would not work for cards in piles
  client/js/widgets/widget.js
Labels: bug, routine operations

#411 fixed GET sum of empty collection
  client/js/widgets/widget.js
Labels: bug, routine operations
