Repository ArnoldSmith86/virtualtabletop, pull requests merged in 2021-01, with the labels that each got.

#161 autosave rooms once per minute
  server.mjs
  server/room.mjs
Labels: operations

#93 added activePlayers as a preset variable to buttons (fixes #91)
  client/js/overlays/players.js
  client/js/widgets/button.js
Labels: enhancement

#178 preserve white space in widget text
  client/css/layout.css
Labels: enhancement

#172 fixed that removing an update link from a variant would lead to room resets (fixes #169)
  server/room.mjs
Labels: bug

#163 handle property missing in GET first
  client/js/widgets/button.js
Labels: bug

#188 increased the JSON file size limit to 20MB
  server/fileloader.mjs
Labels: enhancement
