Repository ArnoldSmith86/virtualtabletop, pull requests merged in 2021-06, with the labels that each got.

#527 added favicon
  assets/branding/favicon.png
  assets/branding/favicon.svg
  client/room.html
Labels: enhancement

#509 reset z values when above 90000
  client/js/main.js
  client/js/statemanaged.js
  tests/testcafe/tests.js
Labels: enhancement, widget properties

#516 JSON representation and copy in set()
  client/js/statemanaged.js
Labels: enhancement, widget properties

#529 added syntax highlighting for numbers and strings in arrays
  client/js/jsonedit.js
Labels: JSON editor, enhancement

#530 show upload asset button for more properties
  client/js/jsonedit.js
Labels: JSON editor, enhancement

#535 fixed server crash after PR #530
  client/js/jsonedit.js
Labels: bug

#514 use native events to check ctrlKey
  client/js/jsonedit.js
  client/js/mousehandling.js
Labels: JSON editor, enhancement

#525 added FOREACH
  client/js/jsonedit.js
  client/js/widgets/widget.js
  server/fileupdater.mjs
Labels: enhancement, routine operations

#520 holding CTRL in JSON editor allows moving widgets
  client/js/mousehandling.js
Labels: JSON editor, enhancement

#523 added multi-selection mode to JSON editor
  client/js/jsonedit.js
Labels: JSON editor, enhancement

#435 Set owner on pile creation
  client/js/widgets/pile.js
  client/js/widgets/widget.js
Labels: Ready for review

#522 enhanced widget duplication in JSON editor
  client/js/domhelpers.js
  client/js/editmode.js
  client/js/jsonedit.js
  client/js/widgets/widget.js
  tests/testcafe/tests.js
Labels: JSON editor, enhancement

#563 Fix for collapsing labels
  client/css/widgets/label.css
Labels: Ready for review

#444 added canvas
  client/css/editmode.css
  client/css/widgets/canvas.css
  client/js/editmode.js
  client/js/jsonedit.js
  client/js/mousehandling.js
  client/js/serverstate.js
  client/js/widgets/canvas.js
  client/js/widgets/widget.js
  client/room.html
  server/minify.mjs
Labels: enhancement

#559 fixed phantom widgets after removal
  client/js/editmode.js
  client/js/jsonedit.js
  client/js/widgets/widget.js
Labels: bug

#560 variables playerName and playerColor are now writable
  client/js/widgets/widget.js
  server/room.mjs
Labels: enhancement, routine operations

#547 fixed crashes in JSON editor when having inconsistent indentation
  client/js/jsonedit.js
Labels: JSON editor, bug

#591 Fix `twoRowBottomAlign`
  client/js/widgets/label.js
Labels: Ready for review, bug

#583 fixed fileupdater crash for string routine entries
  server/fileupdater.mjs
Labels: bug

#552 added command to center widget in parent
  client/js/jsonedit.js
Labels: JSON editor, enhancement

#566 improve enforcement of valid parent
  client/js/editmode.js
  client/js/jsonedit.js
Labels: JSON editor, bug

#469 help for dynamic expressions in JSON Editor
  client/css/jsonedit.css
  client/js/compute.js
  client/js/jsonedit.js
  client/js/main.js
  client/js/widgets/widget.js
  server/minify.mjs
  tests/testcafe/tests.js
Labels: JSON editor, enhancement, routine operations

#600 fixed server crash after #552
  client/js/jsonedit.js
Labels: bug

#573 Fix `CLONE` cannot set `id`
  client/js/widgets/widget.js
Labels: bug, routine operations

#601 added an automated test that checks if the server starts with production settings
  .github/workflows/production-environment.yml
Labels: enhancement, maintenance

#598 fixed undefined collections after `FOREACH`
  client/js/widgets/widget.js
Labels: bug, routine operations

#457 Basic UI redesign
  client/components/baseEditOverlay.js
  client/components/deckEditor.js
  client/css/editmode.css
  client/css/layout.css
  client/js/editmode.js
  client/js/main.js
  client/room.html
  tests/testcafe/tests.js
Labels: enhancement, user interface
