Repository ArnoldSmith86/virtualtabletop, pull requests merged in 2021-10, with the labels that each got.

#728 SET = instead of + if value is null
  client/js/widgets/widget.js
Labels: routine operations

#737 Adds cardType & deck to mouse over in JSON editor
  client/js/jsonedit.js
Labels: enhancement, JSON editor

#762 Retain order of top 2 cards SET to new parent
  client/js/widgets/widget.js
  tests/testcafe/tests.js
Labels: enhancement, pile related

#790 hide inactive guests from player list
  server/room.mjs
Labels: enhancement, user interface

#771 Correctly process 'return: false' in debugging. Fixes #767
  client/js/widgets/widget.js
Labels: JSON editor

#796 Fix editing cards directly in JSON editor
  client/js/jsonedit.js
Labels: bug

#789 improve cacheability of assets
  server.mjs
Labels: enhancement, maintenance

#531 added _ancestor pseudo property
  client/js/widgets/widget.js
Labels: enhancement, widget properties, pile related

#806 Add 'intersect' and 'remove' as modes for SELECT
  client/js/jsonedit.js
  client/js/widgets/widget.js
Labels: enhancement, routine operations

#777 Add array of objects to dropTarget
  client/js/domhelpers.js
  client/js/main.js
  client/js/widgets/holder.js
  server/fileupdater.mjs
Labels: enhancement, needs file version bump, widget properties

#821 Prevent owner change when childrenPerOwner false
  client/js/widgets/widget.js
Labels: enhancement, widget properties

#817 Reuse edit mode add widget screen in JSON editor
  client/components/deckEditor.js
  client/css/editmode.css
  client/js/editmode.js
  client/js/jsonedit.js
  client/js/widgets/widget.js
  client/room.html
  tests/testcafe/tests.js
Labels: enhancement, JSON editor, Ready for review, needs testing
