Repository ArnoldSmith86/virtualtabletop, pull requests merged in 2022-04, with the labels that each got.

#1195 fix spinner bugs
  client/js/widgets/spinner.js
Labels: bug

#1204 remove Hearts.vtt
  Hearts.vtt
Labels: bug, library

#1180 apply styles in widget stylesheet to `#enlarged`
  client/css/jsonedit.css
  client/css/layout.css
  client/js/main.js
  client/js/mousehandling.js
  client/js/widgets/widget.js
  client/room.html
Labels: bug, enhancement
