Repository ArnoldSmith86/virtualtabletop, pull requests merged in 2022-12, with the labels that each got.

#1432 Add 'range' option to FOREACH
  client/js/jsonedit.js
  client/js/widgets/widget.js
Labels: enhancement, routine operations

#1424 Allow array of holders in COUNT, array of canvas in CANVAS.
  client/js/widgets/widget.js
Labels: bug, routine operations

#1411 CSV support for decks
  client/js/jsonedit.js
Labels: enhancement, JSON editor

#1467 Add maxX and maxY to JSON Editor Grid Options
  client/js/jsonedit.js
Labels: enhancement, JSON editor

#1472 fixed asset migration
  server/room.mjs
Labels: bug, maintenance

#1474 further fixes to state migration
  library/tutorials/JSON User Guide/0.json
  library/tutorials/JSON User Guide/assets/-108283418_41033
  library/tutorials/JSON User Guide/assets/-1105305608_30250
  library/tutorials/JSON User Guide/assets/-1727868967_16762
  library/tutorials/JSON User Guide/assets/-1781871727_78461
  library/tutorials/JSON User Guide/assets/-311274453_876
  library/tutorials/JSON User Guide/assets/-338142491_207316
  library/tutorials/JSON User Guide/assets/-710166205_29366
  library/tutorials/JSON User Guide/assets/-83346626_22768
  library/tutorials/JSON User Guide/assets/1310557521_72042
  library/tutorials/JSON User Guide/assets/1478848789_20542
  library/tutorials/JSON User Guide/assets/1479011481_9212
  library/tutorials/JSON User Guide/assets/1481013228_182992
  library/tutorials/JSON User Guide/assets/1502865726_277
  library/tutorials/JSON User Guide/assets/158610948_60694
  library/tutorials/JSON User Guide/assets/1908364078_358544
  library/tutorials/JSON User Guide/assets/2017378147_382
  library/tutorials/JSON User Guide/assets/485133131_68080
  library/tutorials/JSON User Guide/assets/822277903_277
  server/room.mjs
Labels: bug, maintenance
