Repository ArnoldSmith86/virtualtabletop, pull requests merged in 2022-05, with the labels that each got.

#1164 fix crash when applying delta
  client/js/serverstate.js
  client/js/widgets/widget.js
Labels: bug, routine operations

#1214 update dependencies
  package-lock.json
  package.json
Labels: npm dependencies

#1165 fix crashes with invalid values for `svgReplaces` and `faces`
  client/js/serverstate.js
  client/js/widgets/basicwidget.js
  client/js/widgets/button.js
  client/js/widgets/timer.js
  client/js/widgets/widget.js
Labels: bug, routine operations, widget properties

#1215 fixed ordering of custom properties with `inheritFrom`
  client/js/jsonedit.js
Labels: bug, JSON editor

#1196 extends various css properties to take simple object form
  client/js/jsonedit.js
  client/js/widgets/card.js
  client/js/widgets/pile.js
  client/js/widgets/spinner.js
Labels: enhancement

#1226 fixed server crash when tracing is enabled
  server/room.mjs
Labels: bug
