Repository ArnoldSmith86/virtualtabletop, pull requests merged in 2022-11, with the labels that each got.

#1374 Change debug output to be a button.
  client/css/jsonedit.css
  client/js/jsonedit.js
  client/room.html
Labels: enhancement, JSON editor

#1362 Split up tests into categories with common helper functions.
  .github/workflows/testcafe-chrome.yml
  .github/workflows/testcafe-firefox.yml
  package.json
  tests/testcafe/editor.js
  tests/testcafe/functions.js
  tests/testcafe/publiclibrary.js
  tests/testcafe/test-util.js
  tests/testcafe/tests.js
Labels: enhancement, maintenance

#1399 fixed client crash when indexing a variable containing null
  client/js/widgets/widget.js
Labels: bug, routine operations

#1409 always send update for deleted properties
  client/js/editmode.js
Labels: bug, JSON editor

#1401 fixed JSON editor client crash when setting grids inside cardDefaults
  client/js/jsonedit.js
Labels: bug, JSON editor
