Repository ArnoldSmith86/virtualtabletop, pull requests merged in 2022-03, with the labels that each got.

#1120 group custom and routine properties in JSON editor
  client/js/jsonedit.js
Labels: enhancement, JSON editor

#1126 add a few examples to the JSON editor macro feature
  client/js/editmode.js
  client/js/jsonedit.js
Labels: enhancement, JSON editor

#1115 Improve testcafe-gitpod
  .gitpod.yml
  tests/testcafe/gitpod-vnc/install.sh
  tests/testcafe/gitpod-vnc/novnc-index.html
  tests/testcafe/gitpod-vnc/start-vnc-session.sh
  tests/testcafe/gitpod.sh
  tests/testcafe/tests.js
Labels: maintenance

#1124 Default values in INPUT select field
  client/js/domhelpers.js
  client/js/jsonedit.js
Labels: enhancement, widget properties

#1133 prevent redirecting to an existing room
  server.mjs
Labels: bug

#1134 make `directories.save` and `directories.assets` in `config.json` work
  server/fileloader.mjs
  server/pcioimport.mjs
  server/room.mjs
Labels: bug

#1112 result of shuffle is no longer ambiguous
  client/js/widgets/pile.js
  client/js/widgets/widget.js
  tests/testcafe/tests.js
Labels: bug

#893 fixed crashes with widget selection in routine operations
  client/js/widgets/widget.js
Labels: bug, routine operations

#1096 fixed pile overlay card count
  client/js/widgets/pile.js
Labels: bug, user interface

#1087 added urlPrefix config parameter
  client/css/fonts.css
  client/css/layout.css
  client/css/overlays/players.css
  client/js/connection.js
  client/js/domhelpers.js
  client/js/main.js
  client/js/overlays/states.js
  client/js/serverstate.js
  client/js/widgets/basicwidget.js
  client/js/widgets/button.js
  client/js/widgets/card.js
  client/js/widgets/pile.js
  client/js/widgets/spinner.js
  client/js/widgets/widget.js
  client/room.html
  config.template.json
  server.mjs
Labels: enhancement, maintenance

#892 no longer send deltas when creating widgets
  client/js/editmode.js
  client/js/serverstate.js
  client/js/widgets/widget.js
  tests/testcafe/tests.js
Labels: bug, needs testing, pile related

#1140 CALL can return falsy value
  client/js/widgets/widget.js
Labels: bug, routine operations

#1156 Revert "Move to seat sets `owner` before moving to `hand`"
  client/js/widgets/holder.js
  client/js/widgets/widget.js
Labels: bug

#1155 fix audio with `urlPrefix`
  client/js/domhelpers.js
Labels: bug, routine operations

#1150 tree view shows identifying properties
  client/js/jsonedit.js
Labels: enhancement, JSON editor

#1149 fix state downloads when using urlPrefix
  client/js/overlays/states.js
Labels: bug

#1142 fix widget stylesheets when using `urlPrefix`
  client/js/widgets/widget.js
Labels: bug, widget properties

#1159 parallelize testcafe tests on GitHub
  .github/workflows/testcafe-chrome.yml
  .github/workflows/testcafe-firefox.yml
Labels: enhancement, maintenance

#1146 listen for touchcancel
  client/js/mousehandling.js
Labels: bug, user interface

#1144 fix that moving a card half out the hand does not update owner
  client/js/widgets/widget.js
Labels: bug

#1143 fix incrementing label by `null`
  client/js/widgets/widget.js
Labels: bug, routine operations

#1148 the default for custom properties should be `null` instead of `undefined`
  client/js/statemanaged.js
Labels: bug, widget properties

#1154 lights off
  client/css/layout.css
  client/js/main.js
  client/room.html
Labels: enhancement, user interface

#1162 fix crash when `CALL`ing invalid widget
  client/js/widgets/widget.js
  server/pcioimport.mjs
Labels: bug, routine operations
