Repository ArnoldSmith86/virtualtabletop, pull requests merged in 2023-02, with the labels that each got.

#1560 add new jokers and new card back; add license info
  assets/cards-default/1J.svg
  assets/cards-default/2J.svg
  assets/cards-default/3B.svg
  assets/cards-default/3J.svg
  assets/cards-default/4J.svg
  assets/cards-default/license.md
  client/js/editmode.js
  tests/testcafe/editor.js
Labels: enhancement

#1583 fixed re-saving a savegame if the source game is no longer there
  client/js/overlays/states.js
  server/room.mjs
Labels: bug

#1584 fixed wrong logo height on oldish Android
  client/css/layout.css
Labels: bug, user interface

#1571 Use document.elementsFromPoint for JSON editor targets.
  client/css/jsonedit.css
  client/css/layout.css
  client/css/widgets/deck.css
  client/js/jsonedit.js
Labels: bug, JSON editor

#1589 Use the offset from the transform origin to calculate move delta.
  client/js/geometry.js
  client/js/widgets/widget.js
Labels: bug

#1591 Only transition widgets which weren't just created.
  client/js/widgets/widget.js
Labels: bug

#1607 fixed crash when unloading rooms
  server/room.mjs
Labels: bug

#1611 Adjust destination transform by element transform origin - fixes #1603
  client/js/geometry.js
Labels: bug

#1614 check that CALL.routine is string
  client/js/widgets/widget.js
Labels: bug, routine operations

#1618 Behave as if fixedParent is true if only movable in edit
  client/js/widgets/widget.js
Labels: enhancement, JSON editor

#1634 Tutorial - Update `INPUT` with palette
  library/tutorials/Functions - INPUT/0.json
Labels: library

#1645 Update Readme with valid Discord link
  README.md
Labels: bug

#1648 fixed symbol picker
  assets/fonts/symbols.json
Labels: bug, user interface

#1650 update similar to name of Universal
  library/games/Universal/0.json
Labels: enhancement, library

#1649 fixed save states without version
  server/room.mjs
Labels: bug

#1593 added `gameStartRoutine`
  client/js/overlays/states.js
  client/js/serverstate.js
  client/js/widgets/widget.js
  library/games/The Team II/0.json
  library/games/The Team II/1.json
  library/games/The Team II/2.json
  library/games/The Team II/3.json
  server/player.mjs
  server/room.mjs
Labels: enhancement, routine operations, widget properties

#1644 update fantasy wars second try
  library/games/Fantasy Wars/0.json
  library/games/Fantasy Wars/1.json
  library/games/Fantasy Wars/assets/-157838634_610437
  library/games/Fantasy Wars/assets/1421200389_875210
  library/games/Fantasy Wars/assets/630576602_946062
  library/games/Fantasy Wars/assets/713444852_849984
Labels: library

#1606 PL: Spin 5, Fix CSS Transitions
  library/games/Spin 5/0.json
  library/games/Spin 5/1.json
Labels: bug, library

#1551 Public Library: Add Fowl Play
  library/games/Fowl Play/0.json
  library/games/Fowl Play/assets/-1738502711_2343
  library/games/Fowl Play/assets/-2110476494_2560
  library/games/Fowl Play/assets/1206683833_6045
  library/games/Fowl Play/assets/1569326218_2938
  library/games/Fowl Play/assets/1671096424_450159
  library/games/Fowl Play/assets/256008871_3150
  library/games/Fowl Play/assets/297240859_28866
  library/games/You Can't Draw/0.json
Labels: library

#1653 PL Tutorial Update: Routines - Add gameStartRoutine variant
  library/tutorials/Routines/0.json
  library/tutorials/Routines/1.json
  library/tutorials/Routines/2.json
  library/tutorials/Routines/3.json
  library/tutorials/Routines/4.json
  library/tutorials/Routines/5.json
Labels: library

#1637 Apply offset to cloned widget even if no parent exists.
  client/js/widgets/widget.js
  tests/testcafe/publiclibrary.js
Labels: bug, routine operations

#1636 Add option to clone recursively - fixes #1343
  client/js/jsonedit.js
  client/js/widgets/widget.js
Labels: enhancement, routine operations

#1602 fixed dragging text
  client/js/overlays/states.js
Labels: bug, user interface, JSON editor
