Repository ArnoldSmith86/virtualtabletop, pull requests merged in 2023-09, with the labels that each got.

#1816 Public Library - Add Great Greece
  library/games/Great Greece/0.json
  library/games/Great Greece/assets/-1009840976_2182
  library/games/Great Greece/assets/-1016487660_4371
  library/games/Great Greece/assets/-1029929025_29246
  library/games/Great Greece/assets/-10577771_9418
  library/games/Great Greece/assets/-1221954931_225400
  library/games/Great Greece/assets/-1229101722_6998
  library/games/Great Greece/assets/-1308479704_2019
  library/games/Great Greece/assets/-1400320040_2474
  library/games/Great Greece/assets/-1457059290_30563
  library/games/Great Greece/assets/-1515671562_223254
  library/games/Great Greece/assets/-156392233_232384
  library/games/Great Greece/assets/-156642727_1370922
  library/games/Great Greece/assets/-1788848617_1431
  library/games/Great Greece/assets/-1910625717_30241
  library/games/Great Greece/assets/-1944095788_18196
  library/games/Great Greece/assets/-2117793558_237800
  library/games/Great Greece/assets/-2133282075_2267
  library/games/Great Greece/assets/-273717236_9397
  library/games/Great Greece/assets/-275435519_2638
  library/games/Great Greece/assets/-485849516_230711
  library/games/Great Greece/assets/-543816414_324800
  library/games/Great Greece/assets/-629251329_226123
  library/games/Great Greece/assets/-646607464_2242
  library/games/Great Greece/assets/-695127256_31124
  library/games/Great Greece/assets/-761751296_2670
  library/games/Great Greece/assets/-789727638_4379
  library/games/Great Greece/assets/-874944435_5218
  library/games/Great Greece/assets/-936124024_1977
  library/games/Great Greece/assets/-943112176_2149
  library/games/Great Greece/assets/1205787877_16941
  library/games/Great Greece/assets/1207997856_956859
  library/games/Great Greece/assets/1218225602_223086
  library/games/Great Greece/assets/1277029730_2223
  library/games/Great Greece/assets/1291543607_4380
  library/games/Great Greece/assets/1312160563_3337
  library/games/Great Greece/assets/1333760315_2655
  library/games/Great Greece/assets/1587959710_237463
  library/games/Great Greece/assets/1755734387_1962
  library/games/Great Greece/assets/1951073475_1926
  library/games/Great Greece/assets/206129680_1734
  library/games/Great Greece/assets/309415826_15768
  library/games/Great Greece/assets/358768744_230034
  library/games/Great Greece/assets/504887717_238937
  library/games/Great Greece/assets/711208508_234519
  library/games/Great Greece/assets/884478070_4381
  library/games/Great Greece/assets/889110884_2093
Labels: library

#1820 fixed minification
  client/js/jsonedit.js
  client/js/overlays/states.js
  server/minify.mjs
Labels: bug

#1822 Create FUNDING.yml
  .github/FUNDING.yml
Labels: maintenance

#1827 updated dependencies
  package-lock.json
  package.json
Labels: npm dependencies

#1831 added admin overview page
  config.template.json
  server.mjs
Labels: enhancement, maintenance

#1832 added `serverName` to config
  client/js/main.js
  client/room.html
  config.template.json
  server/minify.mjs
Labels: enhancement, maintenance

#1825 fixed adding games with multiple variants to the public library
  server/room.mjs
Labels: bug

#1834 added widget buffer to copy widgets between games
  client/js/editor/layout.js
  client/js/editor/sidebar/toolbox.js
  server/minify.mjs
Labels: enhancement, JSON editor
