Repository ArnoldSmith86/virtualtabletop, pull requests merged in 2024-09, with the labels that each got.

#2275 added compute function `sum`
  client/js/compute.js
  library/tutorials/Arrays/0.json
  library/tutorials/Arrays/1.json
  library/tutorials/Arrays/2.json
  library/tutorials/Arrays/3.json
  library/tutorials/Arrays/4.json
  library/tutorials/Arrays/5.json
Labels: enhancement, routine operations

#2274 Public Library - Add A Night On Town
  library/games/A Night on_ Town/0.json
  library/games/A Night on_ Town/assets/-1637913600_15676
  library/games/A Night on_ Town/assets/-1863666130_159924
  library/games/A Night on_ Town/assets/-2035383264_4506
  library/games/A Night on_ Town/assets/-2121810342_57592
  library/games/A Night on_ Town/assets/1000076354_385
  library/games/A Night on_ Town/assets/1056290557_3350
  library/games/A Night on_ Town/assets/1075909367_10026
  library/games/A Night on_ Town/assets/1189078585_140034
  library/games/A Night on_ Town/assets/1538051551_7758
  library/games/A Night on_ Town/assets/1554193986_7324
  library/games/A Night on_ Town/assets/1828247223_3644
  library/games/A Night on_ Town/assets/1976223680_15506
  library/games/A Night on_ Town/assets/2093193169_9026
  library/games/A Night on_ Town/assets/210826549_17128
  library/games/A Night on_ Town/assets/929442417_5904
Labels: library

#2279 Public Library - Add 8 ballin'
  library/games/8 ballin_/0.json
  library/games/8 ballin_/assets/-1311987001_31753
  library/games/8 ballin_/assets/-1319039034_2443
  library/games/8 ballin_/assets/-1376470531_2443
  library/games/8 ballin_/assets/-1439501723_76156
  library/games/8 ballin_/assets/-1440714291_74237
  library/games/8 ballin_/assets/-1668262670_75007
  library/games/8 ballin_/assets/-1764123906_125120
  library/games/8 ballin_/assets/-1800977298_508271
  library/games/8 ballin_/assets/-1943749866_33784
  library/games/8 ballin_/assets/-62123531_60271
  library/games/8 ballin_/assets/-723958713_2414
  library/games/8 ballin_/assets/-7283580_27642
  library/games/8 ballin_/assets/-758783427_28032
  library/games/8 ballin_/assets/-867935328_71908
  library/games/8 ballin_/assets/-942237377_26680
  library/games/8 ballin_/assets/145697703_54915
  library/games/8 ballin_/assets/1587961295_56756
  library/games/8 ballin_/assets/1747189437_2440
  library/games/8 ballin_/assets/1798344720_49557
  library/games/8 ballin_/assets/1819229853_59795
  library/games/8 ballin_/assets/1875130755_56031
  library/games/8 ballin_/assets/1975435711_53897
  library/games/8 ballin_/assets/2051608096_58870
  library/games/8 ballin_/assets/2101792790_75381
  library/games/8 ballin_/assets/217537111_2443
  library/games/8 ballin_/assets/433173692_61088
  library/games/8 ballin_/assets/549771598_24331
  library/games/8 ballin_/assets/720509150_427229
  library/games/8 ballin_/assets/887846186_55267
Labels: library

#2295 Public Library - Fix Property Tycoon
  library/games/Property Tycoon/0.json
Labels: library

#2287 Public Library - light automation for Runway Roll
  library/games/Runway Roll/0.json
Labels: enhancement, library

#2296 Public Library - fix turn order in Mauer
  library/games/Mauer/0.json
Labels: bug, library

#2290 added Codespaces support
  .devcontainer/devcontainer.json
  .devcontainer/setup.sh
  .vscode/launch.json
Labels: maintenance

#2292 fixed Gitpod
  .gitpod-init.sh
  .gitpod.yml
  .theia/launch.json
  .theia/settings.json
  .vscode/launch.json
Labels: maintenance

#2298 fixed no-repeat typo in hex preset
  client/js/editmode.js
Labels: bug, editor

#2289 fixed undo for JSON editor multi-selection
  client/js/jsonedit.js
Labels: bug, editor

#2276 added `VAR` function for setting raw JSON values to variables
  client/js/jsonedit.js
  client/js/widgets/widget.js
Labels: enhancement, routine operations

#2288 ensure that the game is rendered in light mode
  client/css/editor/layout.css
  client/js/widgets/card.js
Labels: bug, editor

#2204 fixed cloning widgets with inheritFrom
  client/js/widgets/widget.js
Labels: bug, routine operations

#2304 inherit properties again when overriding ones are removed
  client/js/widgets/widget.js
Labels: bug, widget properties

#2300 Public Library - Add VAR tutorial
  library/tutorials/Functions - VAR/0.json
  library/tutorials/Functions - VAR/assets/-1984071267_3512
Labels: library

#2253 Formalize use of dropTarget and dropLimit on non-holder widgets
  client/js/serverstate.js
  client/js/statemanaged.js
  client/js/widgets/holder.js
  client/js/widgets/widget.js
  server/minify.mjs
Labels: documentation, enhancement

#1466 Adds count:"all" and allows count:0
  client/js/jsonedit.js
  client/js/widgets/widget.js
  library/tutorials/Functions - FLIP/0.json
  library/tutorials/Functions - MOVE/0.json
  library/tutorials/Functions - MOVEXY/0.json
  library/tutorials/Functions - ROTATE/0.json
  server/fileupdater.mjs
  tests/testcafe/publiclibrary.js
Labels: enhancement, routine operations

#2269 Adds spinner options
  client/css/editor/sidebarModules.css
  client/js/editor/sidebar/properties.js
Labels: enhancement, user interface, editor

#2260 added multi-selection commands for setting a parent
  client/js/jsonedit.js
Labels: enhancement, editor

#1538 Widgets and routines now notice id change
  client/js/editmode.js
  client/js/main.js
  client/js/serverstate.js
  client/js/widgets/widget.js
Labels: bug, enhancement

#2312 fixed a few crashes when properties have unexpected types
  client/js/editor/sidebar/properties.js
  client/js/jsonedit.js
  client/js/widgets/canvas.js
  client/js/widgets/card.js
  client/js/widgets/pile.js
  client/js/widgets/widget.js
Labels: bug, widget properties

#2313 enforce `id` to be a string
  client/js/jsonedit.js
  client/js/serverstate.js
  client/js/widgets/widget.js
Labels: bug, widget properties

#2316 also update `dropTarget` when a widget `id` changes
  client/js/serverstate.js
Labels: enhancement

#2321 fixed default `count` for `MOVE`
  client/js/widgets/widget.js
Labels: bug, routine operations

#2318 categories for game-icons.net in the symbol picker
  assets/fonts/symbols.json
  client/js/domhelpers.js
Labels: enhancement, user interface

#2325 fixed crash when opening deck properties
  client/js/editor/sidebar/properties.js
Labels: bug, editor
