Repository ArnoldSmith86/virtualtabletop, pull requests merged in 2024-11, with the labels that each got.

#2353 updated testcafe on github
  .github/workflows/testcafe-chrome.yml
  .github/workflows/testcafe-firefox.yml
Labels: bug, maintenance

#2364 PL Searching for Sasquatch - Fix Broken Seat Routines
  library/games/Searching for Sasquatch/0.json
Labels: bug, library

#2359 Fix star number location
  client/css/overlays/states.css
Labels: bug, user interface

#2367 Public Library - Add Mystic Tiles
  library/games/Mystic Tiles/0.json
  library/games/Mystic Tiles/assets/-1306714309_4745
  library/games/Mystic Tiles/assets/-52589506_548214
  library/games/Mystic Tiles/assets/1746095057_101091
Labels: library

#2370 added error handling to the Copy State JSON editor button
  client/js/jsonedit.js
Labels: bug, editor

#2368 fixed star number
  client/css/overlays/states.css
  client/js/domhelpers.js
  client/js/jsonedit.js
  client/js/main.js
  client/js/overlays/welcome.js
Labels: bug, user interface

#2371 added technical details to the client crash overlay
  client/js/tracing.js
  client/room.html
Labels: enhancement

#2376 Add player count to toolbar
  client/css/layout.css
  client/js/overlays/players.js
Labels: enhancement

#2379 Public Library - Add District Development
  library/games/District Development/0.json
  library/games/District Development/assets/1558268581_210080
  library/games/District Development/assets/929442417_5904
Labels: library

#2380 Public Library - Add Green Streams
  library/games/Green Streams/0.json
  library/games/Green Streams/assets/-1011123533_3140
  library/games/Green Streams/assets/-1154482413_19220
  library/games/Green Streams/assets/-1170506838_3230
  library/games/Green Streams/assets/-1535221606_3100
  library/games/Green Streams/assets/-1671721304_10050
  library/games/Green Streams/assets/-364797544_3314
  library/games/Green Streams/assets/-79713834_5066
  library/games/Green Streams/assets/1218340394_2332
  library/games/Green Streams/assets/1498280112_2860
  library/games/Green Streams/assets/1762559708_3240
  library/games/Green Streams/assets/1806557360_2386
  library/games/Green Streams/assets/1824203838_3088
  library/games/Green Streams/assets/2062166832_2202
  library/games/Green Streams/assets/214692248_2274
  library/games/Green Streams/assets/612307628_2184
  library/games/Green Streams/assets/786466074_3912
Labels: library

#2381 Public Library - Update Green Streams
  library/games/Green Streams/0.json
  library/games/Green Streams/assets/449419710_47714
Labels: library
